# This is the inventory file where you can define the IP address of the VMs- Simply replace the IP address and server name.


[onos_machine]
sdn-comtroller ansible_host=35.195.237.116 ansible_user=antonios-icontinuum internal_ip=10.132.0.2

#first define the ip address of the machine where you are going to install onos on it
#info:  "ansible_user=ubuntu" is the server name that ansible is using to do ssh to the remote machine


[mininet_machine]
sdn-comtroller ansible_host=35.195.237.116 ansible_user=antonios-icontinuum internal_ip=10.132.0.2


[sflow_machine]
sdn-comtroller ansible_host=35.195.237.116 ansible_user=antonios-icontinuum internal_ip=10.132.0.2

[masters]
master ansible_host=34.52.158.40 ansible_user=antonios-icontinuum internal_ip=10.132.0.3 tap0_ip=192.168.100.100/24

[workers]
worker1 ansible_host=34.22.252.246 ansible_user=antonios-icontinuum internal_ip=10.132.0.4 tap0_ip=192.168.100.101/24

[kubernetes:children]
masters
workers

